serial:
  # 串口配置
  port: COM11  # 可选，如果不指定则自动查找
  baud_rate: 115200  # 可选，默认 115200
  timeout: 1.0  # 可选，默认 1.0

prompts:
  # 自定义提示词配置
  set_pwm_max: "把PWM调到最大"
  set_pwm_min: "把PWM调到最小"
  set_pwm_percent: "请将PWM设置为{value}%"
  # 可以添加更多自定义提示词
  turn_off: "关闭PWM"
  half_power: "把PWM调到一半"
